version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports: ["3000:3000"]
    depends_on:
      - menu-services
      - order-services
      - payment-services
      - inventory-services
      - customer-services

  menu-services:
    build: ./menu-services
    container_name: menu-services
    depends_on: [ mongodb ]

  order-services:
    build: ./order-services
    container_name: order-services
    depends_on:
      - mongodb
      - menu-services
      - inventory-services
      - customer-services

  payment-services:
    build: ./payment-services
    container_name: payment-services
    depends_on:
      - mongodb
      - order-services

  inventory-services:
    build: ./inventory-services
    container_name: inventory-services
    depends_on: [ mongodb ]

  customer-services:
    build: ./customer-services
    container_name: customer-services
    depends_on: [ mongodb ]

volumes:
  mongo-data:
