version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-api-gateway:latest
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service

  menu-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-menu-service:latest
    container_name: menu-service
    depends_on: [ mongodb ]

  order-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-order-service:latest
    container_name: order-service
    depends_on:
      - mongodb
      - menu-service
      - inventory-service
      - customer-service

  payment-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-payment-service:latest
    container_name: payment-service
    depends_on:
      - mongodb
      - order-service

  inventory-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-inventory-service:latest
    container_name: inventory-service
    depends_on: [ mongodb ]

  customer-service:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-customer-service:latest
    container_name: customer-service
    depends_on: [ mongodb ]

volumes:
  mongo-data:
