version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports: ["27017:27017"]
    volumes: [ mongo-data:/data/db ]

  api-gateway:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-api-gateway:latest
    container_name: api-gateway
    ports: ["3000:3000"]
    depends_on:
      - menu-services
      - order-services
      - payment-services
      - inventory-services
      - customer-services

  menu-services:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-menu-services:latest
    container_name: menu-services
    depends_on: [ mongodb ]

  order-services:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-order-services:latest
    container_name: order-services
    depends_on:
      - mongodb
      - menu-services
      - inventory-services
      - customer-services

  payment-services:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-payment-services:latest
    container_name: payment-services
    depends_on:
      - mongodb
      - order-services

  inventory-services:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-inventory-services:latest
    container_name: inventory-services
    depends_on: [ mongodb ]

  customer-services:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/cafe-customer-services:latest
    container_name: customer-services
    depends_on: [ mongodb ]

volumes:
  mongo-data:
