name: Build‑only check            # makes sure every service still builds

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc:
          - api-gateway
          - menu-service
          - order-service
          - payment-service
          - inventory-service
          - customer-service

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.svc }}
        run: |
          docker build -t test-${{ matrix.svc }} ./${{ matrix.svc }}
